# Generated by Django 2.2.1 on 2019-05-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('typeName', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('inDate', models.DateField(auto_now_add=True)),
                ('buyDate', models.DateField()),
                ('use', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=20)),
                ('uage', models.IntegerField()),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=20)),
                ('uage', models.IntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('sclass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=20)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5)),
                ('des', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Device')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRecord', to='lab.Student')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.CharField(max_length=20)),
                ('rtype', models.CharField(max_length=20)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5, null=True)),
                ('des', models.CharField(max_length=200)),
                ('num', models.IntegerField(null=True)),
                ('buyDate', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
                ('totalprice', models.FloatField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabAdmin')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='manufactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Manufactor'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Student'),
        ),
        migrations.CreateModel(
            name='AdminRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=20)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5, null=True)),
                ('des', models.CharField(max_length=200)),
                ('fixtime', models.DateTimeField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabAdmin')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Admincheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=5)),
                ('dealtime', models.DateTimeField(auto_now=True)),
                ('des', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.LabAdmin')),
                ('studentRecord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminCheck', to='lab.StudentRecord')),
            ],
        ),
    ]
